NeuralNetwork/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("neuralmain.urls")),
]

if settings.DEBUG:
    """If Debug mode available, get access to media folder from site"""
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NeuralNetwork/apps/neuralmain/models.py
"""NeuralMain app models"""
import re

from datetime import datetime
# from django.contrib.auth import forms
from django.db import models
# from django import forms


def get_photo_group(self):
    """Returns the match name for a tag
    Returns:
        - :photo_group: lowercase of type plants
    """
    return re.sub("\W+" , "", self.photo_group.lower())


class PhotoRequest(models.Model):
    """ Request model
    Parameters:
        - :photo_name(CharField): name of upload photo
        - :photo_date(DateTimeField): datetime of upload photo
        - :photo_file(ImageField): img file
    """
    photo_name = models.CharField("Имя фотографии", max_length=50, default='')
    photo_date = models.DateTimeField("Дата загрузки фото", default=datetime.now())
    photo_file = models.ImageField("Файл изображения", upload_to="requests/")

    def __str__(self):
        """ Function return string: Photo name | datetime"""
        return self.photo_name+"|"+str(self.photo_date)


class PhotoToDatabase(models.Model):
    """ Model of the plant object sent to the database
    Parameters:
        - :photo_name(CharField): name of upload photo
        - :photo_author(CharField): author of photo
        - :photo_group(CharField): type of plant
        - :photo_author_ip(GenericIPAddressField): author IP-address
        - :photo_date(DateTimeField): field for get Datetime(fill automatic)
        - :photo_file(ImageField): img file
    """
    photo_name = models.CharField("Имя файла", max_length=60, default='')
    photo_author = models.CharField("Автор фотографии", max_length=50)
    photo_group = models.CharField("Вид растения", max_length=20)
    photo_author_ip = models.GenericIPAddressField("ip-адрес автора", default='0.0.0.0')
    photo_date = models.DateTimeField("Дата и время загрузки фото", default='1111-11-11 11:11:11', max_length=25)
    photo_file = models.ImageField("Файл изображения", upload_to="img_to_database/")

    def __str__(self):
        """ Function for show in Adminpanel"""
        return f'{self.photo_group} — {str(self.photo_date.__format__("%d.%m // %H:%M | %Y"))} by "{self.photo_author}"'

class Auth(models.Model):
    """ Authentication model
    Parameters:
        - :login_field(CharField): User login
        - :password_field(CharField): User password
    """
    login_field = models.CharField("Login", max_length=30)
    password_field = models.CharField("Password", max_length=32)  # , widget=forms.PasswordInput
    login_date = models.DateTimeField("Дата и время авторизации", default='1111-11-11 11:11:11', max_length=25)
    # access_field = models.CharField("Контрольное поле", default=None, max_length=25)

    def __str__(self):
        """ Function for show in Adminpanel"""
        return f'{self.login_field} — {str(self.login_date.strftime("%d.%m // %H:%M | %Y"))}'


class Contacts(models.Model):
    """ Feedback model
    Parameters:
         - :user_email(EmailField): user email address
         - :message_field(TextField): user message
         - :author_ip(GenericIPAddressField): author IP-address
    """
    user_email = models.EmailField("Емаил пользователя")
    theme_field = models.CharField("Тема обращения", max_length=150)
    message_field = models.TextField("Сообщение", max_length=500)
    author_ip = models.GenericIPAddressField("ip адресс пользователя", default='0.0.0.0')

    def __str__(self):
        """ Function return user email + theme"""
        if len(self.user_email) > 35:
            # if email length more than 35 - make shorten
            email_splitted = self.user_email.split("@", 1)
            email = email_splitted[0][0:20]+'... @'+email_splitted[1]
        else: email = self.user_email
        return f'From: "{email}" — <{self.theme_field[0:35]}...>'

templates/website/about.html
{% extends 'website/pattern.html' %}
{% load static %}

{% block page_name %}
    О нас
{% endblock %}

{% block current_about %}menu-button-current{% endblock %}

{% block content %}
    <h1>О проекте</h1>
    <p>Leaf Spectator - сервис, созданный для распознавания растений на основе фотографии:</p>
    <ul class="list">
        <li>Создан в 2020 году;</li>
        <li>Время обработки около 1с.;</li>
        <li>Более 30 видов растений в базе данных;</li>
        <li>Более 5000 изображений растений!</li>
{#        <li>Много поситителей в месяц);</li>#}
    </ul>
    <p>
        Мы принимаем все идеи, предложения и критику. Напишите нам на
        <a href="mailto:leafspectator@gmail.com" title="Написать нам на электронный ящик">email</a>
        или через <a href="/contacts" title="Заполнить форму">форму</a> обратной связи.
    </p>
    <br/><p>Создателем проекта является Никита (Mechanoid) Востриков.</p>

{% endblock %}

templates/website/auth.html
{% extends 'website/pattern.html' %}

{% block page_name %}
    Авторизация
{% endblock %}

{% block current_auth %}menu-button-current{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if error %}
            <div class="error-message">
                <p>{{ error }}</p>
            </div>
        {% else %}
            {% if message %}
                <div class="info-message">
                    <p>{{ message }}</p>
                </div>
            {% endif %}
        {% endif %}

    <div class="auth-page-fields">
        {% if not message %}
        <text>Логин: </text><p class="page-obj"><input type="text" name="login_field" minlength="4" maxlength="30" required="" id="id_login_field"><br></p>
        <text>Пароль: </text><p class="page-obj"><input type="password" name="password_field" minlength="6" maxlength="32" required="" id="id_password_field"><br></p>
        <button type="submit" style="align-content: center" class="but-submit" title="">Войти</button>
        {% else %}
            {% if access %}
                <h2 style="padding-bottom: 1em;">Нажмите кнопку, чтоб переобучить систему</h2>
                <text class="page-obj">Введите 'Подтвердить' в поле ниже для подтверждения:</text><br/>
                <p class="page-obj"><input type="text" name="access_field" maxlength="30" pattern="[Пп]одтвердить" id="id_access_field"><br></p>
                <button style="align-content: center">Переобучить</button>
            {% endif %}
        {% endif %}
    </div>

    </form>
{% endblock %}

templates/website/contacts.html
{% extends 'website/pattern.html' %}

{% block page_name %}
    Контакты
{% endblock %}
{% block current_contacts %}menu-button-current{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        <h1>Связаться с нами</h1>
        <h2>Укажите свой e-mail адрес и сообщение для нас.
            Это может быть пожелание, сообщение про найденный баг либо иное обращение</h2>

        {% csrf_token %}
        {% if error %}
            <div class="error-message">
                <p>{{ error }}</p>
            </div>
        {% else %}
            {% if message %}
                <div class="info-message">
                    <p>{{ message }}</p>
                </div>
            {% endif %}
        {% endif %}

        <text>E-mail адрес: </text><p class="page-obj"><input type="email" name="user_email" maxlength="254" required id="id_user_email" pattern="[-.A-Za-z0-9]{3,64}@[A-Za-z0-9-]{2,128}.[A-Za-z]{2,4}"></p>
{#        <text>Тема письма: </text><p class="page-obj">{{ form.theme_field }}</p>#}
        <text>Тема письма: </text><p class="page-obj"><input type="text" name="theme_field" minlength="5" maxlength="80" required="" id="id_theme_field"></p>
        <text>Сообщение: </text><p class="page-obj"><textarea name="message_field" cols="40" rows="10" minlength="15" maxlength="500" required="" id="id_message_field"></textarea></p>
        <button style="align-content: center" class="but-submit">Отправить</button>


    </form>
{% endblock %}

templates/website/faq.html
{% extends 'website/pattern.html' %}
{% load static %}

{% block page_name %}
    FAQ
{% endblock %}

{% block content %}
    <h1>FAQ</h1>
    <p class="faq-ask">1.1) Как я могу определить растение по фото?</p>
    <p class="faq-answer">Перейдите на <a href="/">главную</a> страницу, в соответствующем поле нажмите на кнопку для выбора файла, после чего нажмине на кнопку "Проверить!"</p>

    <p class="faq-ask">1.2) Какую фотографию необходимо загружать?</p>
    <p class="faq-answer">Необходимо загружать фото листка растения.</p>

    <p class="faq-ask">1.3) Как необходимо фотографировать лист?</p>
    <p class="faq-answer">Для точного определения нужно держать лист вертикально, чтоб корень листка был к низу изображения.</p>

    <p class="faq-ask">1.4) Почему мой лист не определяется?</p>
    <p class="faq-answer">Проверьте качество изображения, лист должен находится в фокусе, хорошо освещён и расположен вертикально, корнем к низу. Также, возможно, вашего вида растения нет в базе данных.</p>

    <p class="faq-ask">1.5) Почему система не принимает мое изображение?</p>
    <p class="faq-answer">Убедитесь, что Ваш файл - не приложение или иной исполняемый файл. Возможно файл повреждён, попробуйте открыть его и просмотреть. Если проблема не решена - <a href="/contacts">свяжитесь с нами.</a></p>

    <p class="faq-ask">2.1) Зачем мне выгружать фото?</p>
    <p class="faq-answer">Вы можете помочь проекту, если у вас есть качестенная фотография листка растения и вы знаете его вид.</p>

    <p class="faq-ask">2.2) Какие требования к изображению?</p>
    <p class="faq-answer">Смотреть п1.3-1.5</p>

    <p class="faq-ask">2.3) Моё изображение будет принято?</p>
    <p class="faq-answer">Изображение пройдёт модерацию и в случае успешной проверки - будет добавлено в базу данных.</p>

    <p class="faq-ask">3.1) Как мне войти/зарегистрироваться?</p>
    <p class="faq-answer">На текущем этапе вход доступен только модераторам и администратору.</p>

    <p class="faq-ask">3.2) Как стать модератором?</p>
    <p class="faq-answer">Сейчас набор закрыт, в будущем заявки будут приниматься через форму <a href="/contacts">обратной связи.</a></p>

    <p class="faq-ask">4.1) Молу ли я принять участие в проекте?</p>
    <p class="faq-answer">Связитесь с нами. <a href="/contacts" title="Страница обратной связи">Тут</a> или <a href="mailto:leafspectator@gmail.com" title="Написать электронное письмо">тут.</a></p>

    <p class="faq-ask">5.1) Куда попадёт моё письмо?</p>
    <p class="faq-answer">Все обращения хранятся у нас на сервере и рассматриваются в порядке очереди.</p>
{% endblock %}

templates/website/main.html
{% extends 'website/pattern.html' %}
{% load static %}

{% block page_name %}
    Главная
{% endblock %}

{% block current_main %}menu-button-current{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h1>Мы попробуем опознать ваше растение.</h1>
        <h2>Загрузите фото в форму ниже.<br/>Загружайте фотографию всего листа растения, держа лист вертикально и в фокусе.</h2>
        <div>
        {% if error %}
            <div class="error-message">
                <p>{{ error }}</p>
            </div>
        {% else %}
            {% if message %}
                <div class="info-message">
                    <p>{{ message }}</p>
                </div>
            {% endif %}
        {% endif %}
        </div>
        <div class="main-page-select-block">
            <div>{{ form.photo_file }}</div>
            <button type="submit" style="width: 40%" title="Запустить анализ изображения">Проверить!</button>
        </div>
    </form>
{% endblock %}

templates/website/main_upload.html
{% load static %}
{#{% load media %}#}

<!DOCTYPE html><!-- HTML5 -->
<html prefix="og: http://ogp.me/ns#" lang="ru-RU" dir="ltr">
	<head>
        <style>.button7{
          font-weight: 700;
          color: white;
          text-decoration: none;
          padding: .8em 1em calc(.8em + 3px);
          border-radius: 3px;
          background: rgb(64,199,129);
          box-shadow: 0 -3px rgb(53,167,110) inset;
          transition: 0.2s;
        }
        .button7:hover { background: rgb(53, 167, 110); }
        .button7:active {
          background: rgb(33,147,90);
          box-shadow: 0 3px rgb(33,147,90) inset;
        }</style>

		<title>Главная - Leaf spectator - Leaf spectator</title>
		<meta charset="utf-8" />
		<!--[if IE]><meta http-equiv="ImageToolbar" content="False" /><![endif]-->
		<meta name="author" content="Mechanoid" />
		<meta name="generator" content="Incomedia WebSite X5 Professional 12.0.6.24 - www.websitex5.com" />
		<meta name="description" content="Main page Leaf spectator" />
		<meta property="og:locale" content="ru-RU" />
		<meta property="og:type" content="website" />
		<meta property="og:url" content="http://leafspec.com/index.html" />
		<meta property="og:title" content="Главная" />
		<meta property="og:site_name" content="Leaf spectator" />
		<meta property="og:description" content="Main page Leaf spectator" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="icon" href="{% static 'favicon.png' %}" type="image/png" />
		<link rel="stylesheet" type="text/css" href="{% static 'style/reset.css' %}" media="screen,print" />
		<link rel="stylesheet" type="text/css" href="{% static 'style/print.css' %}" media="print" />
		<link rel="stylesheet" type="text/css" href="{% static 'style/style.css' %}" media="screen,print" />
		<link rel="stylesheet" type="text/css" href="{% static 'style/template.css' %}" media="screen" />
		<link rel="stylesheet" type="text/css" href="{% static 'style/menu.css' %}" media="screen" />
		<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="style/ie.css?12-0-6-24" media="screen" /><![endif]-->
		<link rel="stylesheet" type="text/css" href="{% static 'pcss/main.css' %}" media="screen" />
		<!--[if lt IE 9]><link rel="stylesheet" type="text/css" href="{% static 'main.cssmain.cssa' %}="screen" /><![endif]-->
		
{#		<script type="text/javascript" src="{% static 'res/jquery.js' %}"></script>#}
{#		<script type="text/javascript" src="{% static 'res/x5engine.js' %}" data-files-version="12-0-6-24"></script>#}
		
		
		
		<script type="text/javascript">
			x5engine.boot.push(function () { x5engine.utils.imCodeProtection('Mechanoid'); });
			x5engine.boot.push(function () { x5engine.utils.checkBrowserCompatibility(); });
		</script>
		
	</head>
	<body>
		<div id="imHeaderBg"></div>
		<div id="imFooterBg"></div>
		<div id="imPage">
			<div id="imHeader">
				<h1 class="imHidden">Главная - Leaf spectator - Leaf spectator</h1>
				
			</div>
			<a class="imHidden" href="#imGoToCont" title="Заголовок главного меню">Перейти к контенту</a>
			<a id="imGoToMenu"></a><p class="imHidden">Главное меню:</p>
			<div id="imMnMnGraphics"></div>
			<div id="imMnMn" class="auto">
				<div class="hamburger-site-background menu-mobile-hidden"></div><div class="hamburger-button"><div><div><div class="hamburger-bar"></div><div class="hamburger-bar"></div><div class="hamburger-bar"></div></div></div></div><div class="hamburger-menu-background-container"><div class="hamburger-menu-background menu-mobile-hidden"><div class="hamburger-menu-close-button"><span>&times;</span></div></div></div>
				<span itemscope itemtype="http://schema.org/Attorney"><a itemprop="url" href="main.html"><img src="{% static 'style/responsive-logo.png' %}" itemprop="logo" class="menu-mobile-logo" alt="Leaf spectator"/></a>
				</span><ul class="auto menu-mobile-hidden">
					<li id="imMnMnNode0" class="imPage imMnMnCurrent">
						<a href="/">
							<span class="imMnMnFirstBg">
								<span class="imMnMnTxt"><span class="imMnMnImg"></span><span class="imMnMnTextLabel">Главная</span></span>
							</span>
						</a>
					</li><li id="imMnMnNode3" class=" imPage">
						<a href="/upload/">
							<span class="imMnMnFirstBg">
								<span class="imMnMnTxt"><span class="imMnMnImg"></span><span class="imMnMnTextLabel">Выгрузить фото</span></span>
							</span>
						</a>
					</li><li id="imMnMnNode4" class=" imPage">
						<a href="/auth/">
							<span class="imMnMnFirstBg">
								<span class="imMnMnTxt"><span class="imMnMnImg"></span><span class="imMnMnTextLabel">Авторизация</span></span>
							</span>
						</a>
					</li><li id="imMnMnNode7" class=" imPage">
						<a href="/contacts/">
							<span class="imMnMnFirstBg">
								<span class="imMnMnTxt"><span class="imMnMnImg"></span><span class="imMnMnTextLabel">Контакты</span></span>
							</span>
						</a>
					</li></ul>
			</div>
			<div id="imContentGraphics"></div>
			<div id="imContent">
				<a id="imGoToCont"></a>
				<div id="imGroup_1" class="imVGroup">
				<div id="imGroup_2" class="imHGroup">
				<div id="imCell_1"><div id="imCellStyleGraphics_1"></div><div id="imCellStyle_1" data-responsive-sequence-number="1"><div id="imTextObject_1">
					<div class="text-tab-content"  id="imTextObject_1_tab0" style="text-align: left;">
						<div class="text-inner">
							<div style="text-align: left;"><b class="fs21 cf1">Мы попробуем опознать растение</b></div><div style="text-align: left;"><b class="fs21 cf1"><br></b></div><div style="text-align: right;"><span class="fs15"><span class="fs21">Для распознавания выберите файл, </span></span></div><div style="text-align: right;"><span class="fs15"><span class="fs21">нажав на кнопку справа</span></span></div><div style="text-align: right;"><br></div><div style="text-align: left;"><span class="fs16">Загружайте фотографию всего листа растения, </span></div><div style="text-align: left;"><span class="fs16">держа лист ветрикально и в фокусе.</span></div>
						</div>
					</div>
				
				</div>
				</div></div><div id="imGroup_3" class="imVGroup">
				<div id="imGroup_4" class="imHGroup">
				<div id="imGroup_5" class="imVGroup">
{#				<div id="imCell_4"></div><div id="imCell_3"><div id="imCellStyleGraphics_3"></div><div id="imCellStyle_3" data-responsive-sequence-number="3"><form id="imObjectForm_3" action="/result/" method="get" enctype="multipart/form-data"> {# action="imemail/imEmailForm_36sk1mj7.php" method="post" #}
{#					<fieldset class="first">#}
{#						<div>#}
{#							<div id="imObjectForm_3_1_container" class="imObjectFormFieldContainer"><label id="imObjectForm_3_1_label" for="imObjectForm_3_1">Выберите файл изображения для сканирования:*</label><br />#}
{#                                <div id="imObjectForm_3_1_field">#}
{#				<input type="file" class="mandatory " data-extensions="jpg,png,PNG,jpeg" id="imObjectForm_3_1" name="imObjectForm_3_1" /></div>#}
				</div>
						</div>
					</fieldset>
					<fieldset>
						<input type="text" id="imObjectForm_3_prot" name="imSpProt" />
					</fieldset>

                            <h1>{{ message }}</h1>
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <br>
                                <input type="file" name="img">

                                <button type="submit" id="button7">Upload</button><br/>
                                <p><input type="submit" class="button7" value="Upload2"></p>

{#                                <input type="submit" value="Button">#}
                            </form>
{#                        {% if url %}#}
{#                            <p>Debug mode: your file: <a href="{{ url }}">{{ url }}</a> </p>#}
{#                        {% endif %}#}
				</form>
				<script>x5engine.boot.push('x5engine.imForm.initForm(\'#imObjectForm_3\', false, {type: \'tip\', showAll: true, classes: \'validator\', landingPage: \'index.html\', labelColor: \'#000000\', fieldColor: \'#000000\', selectedFieldColor: \'#000000\'})');</script>
				</div></div>
				</div><div id="imGroup_6" class="imVGroup">
				<div id="imGroup_7" class="imEGroup"></div>
				<div id="imGroup_8" class="imEGroup"></div>
				
				</div>
				</div><div id="imGroup_9" class="imHGroup">
				<div id="imGroup_10" class="imEGroup"></div>
				<div id="imGroup_11" class="imEGroup"></div>
				
				</div>
				</div>
				</div><div id="imCell_2"></div>
				</div>
{#				<div id="imFooPad" style="height: 286px; float: left;">&nbsp;</div><div id="imBtMn"><a href="main.html">Главная</a> | <a href="upload_old.html">Выгрузить фото</a> | <a href="auth.html">Авторизация</a> | <a href="contacts.html">Контакты</a> | <a href="imsitemap.html">Главная Карта Сайта</a></div>#}
				<div class="imClear"></div>
			</div>
			<div id="imFooter">
				
				<div id="imFooterResponsiveContent">All rights reserved. Mechanoid. 2020.</div>
			</div>
		</div>
		<span class="imHidden"><a href="#imGoToCont" title="Прочесть эту страницу заново">Назад к содержимому</a> | <a href="#imGoToMenu" title="Прочесть этот сайт заново">Назад к главному меню</a></span>
		
		<noscript class="imNoScript"><div class="alert alert-red">Для использования этого сайта необходимо включить JavaScript.</div></noscript>
	</body>
</html>

templates/website/pattern.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="Mechanoid" />
    <meta name="description" content="Analyse and detect leaf of plants" />
    <meta name="keywords" content="Leaf, spectator, nature, plants"/>
    <meta property="og:type" content="website" />
    <meta property="og:url" content="http://leafspec.com/" />
    <meta property="og:title" content="LeafSpectator" />
    <meta property="og:site_name" content="Leaf spectator" />
    <link rel="stylesheet" type="text/css" href="{% static '/style/main.css' %}"/>
    <link rel="shortcut icon" href="{% static '/style/image/favicon.png' %}" type="image/x-icon"/>
    <title>{% block page_name %}{% endblock %} - LeafSpectator</title>
</head>
<body>
    {% csrf_token %}
    <div id="page-wrap">
{#    <header class="header-block">#}
    <header>
{#        <div class="main-title">Leaf Spectator</div>#}
        <div class="menu-button-block">
            <a href="/" class="menu-button {% block current_main %}{% endblock %}" title="Главная страница">Главная</a>
            <a href="/upload" class="menu-button {% block current_upload %}{% endblock %}" title="Страница для отправки изображения нам">Выгрузить фото</a>
            <a href="/auth" class="menu-button {% block current_auth %}{% endblock %}" title="Страница авторизации">Авторизация</a>
            <a href="/about" class="menu-button {% block current_about %}{% endblock %}" title="Информация про этот сервис">О проекте</a>
            <a href="/contacts" class="menu-button {% block current_contacts %}{% endblock %}" title="Свяжитесь с нами">Контакты</a><br/>
        </div>
        <div class="main-title-block">
            <a href="/" class="main-title">Leaf Spectator</a>
            <text class="main-title-info">Для тех, кто хочет найти растение</text>
        </div>
    </header>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
    </div>

    <footer>
        <div class="footer-block">
            <span>
                <a href="mailto:leafspectator@gmail.com" class="footer-link-style" title="Написать нам на электронный ящик">Напишите нам!</a>
                <a href="#" class="footer-link-style" title="Приложение находятся в разработке...">Мобильное приложение</a>
                <a href="/FAQ" class="footer-link-style" title="Часто задаваемые вопросы">FAQ</a>
            </span>
            <text class="copyright" title="Механоид&copy; Все права защищены. 2020">Mechanoid&copy; All rights reserved. 2020</text>
        </div>
    </footer>

</body>
</html>

templates/website/upload.html
{% extends 'website/pattern.html' %}

{% block page_name %}
    Выгрузить фото
{% endblock %}
{% block current_upload %}menu-button-current{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h1>Вы можете отправить нам фото листка растения. </h1>
        <h2 style="margin-bottom: 1em">Если изображение будет соответствовать нашим требованиям, оно будет использовано для усовершенствования проекта.</h2>
        {% if error %}
            <div class="error-message">
                <p>{{ error }}</p>
            </div>
        {% else %}
            {% if message %}
                <div class="info-message">
                    <p>{{ message }}</p>
                </div>
            {% endif %}
        {% endif %}
        <span class="upload-page">
            <text>Имя автора: </text><p class="page-obj">{{ form.photo_author }}<br/></p>
            <text>Вид растения: </text><p class="page-obj">{{ form.photo_group }}<br/></p>
            <p class="upload-page-obj">{{ form.photo_file }}</p>
            <button>Отправить</button>
        </span>
{#    <text class="info">Лист должен быть хорошо виден и освещён.<br/>Лист должен находится в центре изображения</text>#}
    <p style="color: #636363">Лист должен быть хорошо виден и освещён.<br/>Лист должен находится в центре изображения.</p>

    </form>
{% endblock %}